# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 14:05
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('message_type', models.CharField(choices=[('UNREAD', 'unread'), ('READ', 'read'), ('EXPIRED', 'expire')], db_index=True, default='unread', max_length=20, verbose_name='message type')),
            ],
            options={
                'db_table': 'inbox',
                'verbose_name': 'inbox',
                'verbose_name_plural': 'inbox',
            },
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('subject', models.CharField(max_length=500, verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
                ('expire_date', models.DateTimeField(verbose_name='expire date')),
            ],
            options={
                'db_table': 'newsletter',
                'verbose_name': 'newsletter',
                'verbose_name_plural': 'newsletter',
            },
        ),
        migrations.AddField(
            model_name='inbox',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='message.NewsLetter', verbose_name='news'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
