# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_historicalinbox_historicalnewsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinbox',
            name='message_type',
            field=models.CharField(choices=[('UNREAD', 'unread'), ('READ', 'read'), ('EXPIRED', 'expired')], db_index=True, default='unread', max_length=20, verbose_name='message type'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='message_type',
            field=models.CharField(choices=[('UNREAD', 'unread'), ('READ', 'read'), ('EXPIRED', 'expired')], db_index=True, default='unread', max_length=20, verbose_name='message type'),
        ),
    ]
