# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 14:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('player_1', models.CharField(max_length=1000, verbose_name='player 1')),
                ('player_1_bot', models.BooleanField(default=False, verbose_name='player 1 is bot')),
                ('player_2', models.CharField(max_length=1000, verbose_name='player 1')),
                ('player_2_bot', models.BooleanField(default=False, verbose_name='player 2 is bot')),
                ('status', models.CharField(choices=[('start', 'start'), ('end', 'end')], default='start', max_length=5, verbose_name='status')),
            ],
            options={
                'db_table': 'battles',
                'verbose_name': 'battle',
                'verbose_name_plural': 'battles',
            },
        ),
    ]
