# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_battletransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battletransaction',
            options={'verbose_name': 'battle transaction', 'verbose_name_plural': 'battle transactions'},
        ),
        migrations.AlterModelTable(
            name='battletransaction',
            table='battle_transaction',
        ),
    ]
