# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-20 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20180519_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='battle_id',
            field=models.CharField(default=None, max_length=200, unique=True, null=True,verbose_name='battle id'),
        ),
    ]
