# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 14:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0070_auto_20180722_1002'),
        ('reports', '0005_auto_20180520_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroopReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('win', models.PositiveIntegerField(default=0, verbose_name='win count')),
                ('lose', models.PositiveIntegerField(default=0, verbose_name='lose count')),
                ('troop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fight_reports', to='objects.Unit', verbose_name='troop')),
            ],
            options={
                'db_table': 'troop_reports',
                'verbose_name': 'troop_report',
                'verbose_name_plural': 'troop_reports',
            },
        ),
        migrations.CreateModel(
            name='UserHeroSummary',
            fields=[
            ],
            options={
                'verbose_name': 'UserHero Summary',
                'proxy': True,
                'verbose_name_plural': 'UserHeroes Summary',
                'indexes': [],
            },
            bases=('objects.userhero',),
        ),
    ]
