# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 15:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('name', models.CharField(max_length=4, verbose_name='name')),
                ('box', models.CharField(choices=[('GEM', 'gem'), ('COIN', 'coin')], max_length=4, verbose_name='box')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
            ],
            options={
                'db_table': 'benefit_box',
                'verbose_name': 'benefit_box',
                'verbose_name_plural': 'benefit_boxes',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('health', models.IntegerField(default=100, verbose_name='health')),
                ('shield', models.IntegerField(default=0, verbose_name='shield')),
                ('attack', models.IntegerField(default=10, verbose_name='attack')),
                ('critical_chance', models.FloatField(default=0.01, verbose_name='critical chance')),
                ('critical_ratio', models.FloatField(default=0.01, verbose_name='critical ratio')),
                ('miss_chance', models.FloatField(default=0.0, verbose_name='miss chance')),
                ('dodge_chance', models.FloatField(default=0.0, verbose_name='dodge chance')),
                ('dexterity', models.CharField(choices=[('MIDDLE', 'middle'), ('LATE', 'late'), ('EARLY', 'early')], default='MIDDLE', max_length=50, verbose_name='dexterity')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('image_logo', models.ImageField(upload_to='hero/logo', verbose_name='image')),
                ('image', models.ImageField(upload_to='hero/image', verbose_name='image')),
            ],
            options={
                'db_table': 'hero',
                'verbose_name': 'hero',
                'verbose_name_plural': 'heroes',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('health', models.IntegerField(default=100, verbose_name='health')),
                ('shield', models.IntegerField(default=0, verbose_name='shield')),
                ('attack', models.IntegerField(default=10, verbose_name='attack')),
                ('critical_chance', models.FloatField(default=0.01, verbose_name='critical chance')),
                ('critical_ratio', models.FloatField(default=0.01, verbose_name='critical ratio')),
                ('miss_chance', models.FloatField(default=0.0, verbose_name='miss chance')),
                ('dodge_chance', models.FloatField(default=0.0, verbose_name='dodge chance')),
                ('dexterity', models.CharField(choices=[('MIDDLE', 'middle'), ('LATE', 'late'), ('EARLY', 'early')], default='MIDDLE', max_length=50, verbose_name='dexterity')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('image_logo', models.ImageField(upload_to='unit/logo', verbose_name='image')),
                ('image', models.ImageField(upload_to='unit/image', verbose_name='image')),
            ],
            options={
                'db_table': 'unit',
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
            },
        ),
    ]
