# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20180224_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='max_health',
            field=models.IntegerField(default=100, verbose_name='max health'),
        ),
        migrations.AddField(
            model_name='hero',
            name='max_shield',
            field=models.IntegerField(default=0, verbose_name='max shield'),
        ),
        migrations.AddField(
            model_name='historicalhero',
            name='max_health',
            field=models.IntegerField(default=100, verbose_name='max health'),
        ),
        migrations.AddField(
            model_name='historicalhero',
            name='max_shield',
            field=models.IntegerField(default=0, verbose_name='max shield'),
        ),
        migrations.AddField(
            model_name='historicalunit',
            name='max_health',
            field=models.IntegerField(default=100, verbose_name='max health'),
        ),
        migrations.AddField(
            model_name='historicalunit',
            name='max_shield',
            field=models.IntegerField(default=0, verbose_name='max shield'),
        ),
        migrations.AddField(
            model_name='unit',
            name='max_health',
            field=models.IntegerField(default=100, verbose_name='max health'),
        ),
        migrations.AddField(
            model_name='unit',
            name='max_shield',
            field=models.IntegerField(default=0, verbose_name='max shield'),
        ),
    ]
