# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20171216_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitbox',
            name='name',
            field=models.CharField(max_length=40, verbose_name='name'),
        ),
    ]
