# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 13:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0004_auto_20171216_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_buy', to='objects.BenefitBox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_buy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='benefitbox',
            name='user',
            field=models.ManyToManyField(related_name='user', through='objects.UserBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
