# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_auto_20180224_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusercard',
            name='cool_down_remaining_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='cool down remaining seconds'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='cool_down_remaining_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='cool down remaining seconds'),
        ),
    ]
