# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20180224_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluserchest',
            old_name='chest_type',
            new_name='chest_monetaryType',
        ),
        migrations.RenameField(
            model_name='userchest',
            old_name='chest_type',
            new_name='chest_monetaryType',
        ),
    ]
