# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_auto_20180224_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='chakra_max_health',
            field=models.IntegerField(default=100, verbose_name='chakra max health'),
        ),
        migrations.AddField(
            model_name='hero',
            name='chakra_max_shield',
            field=models.IntegerField(default=0, verbose_name='chakra max shield'),
        ),
        migrations.AddField(
            model_name='hero',
            name='chakra_moniker',
            field=models.CharField(default='moniker', max_length=50, verbose_name='chakra moniker'),
        ),
        migrations.AddField(
            model_name='historicalhero',
            name='chakra_max_health',
            field=models.IntegerField(default=100, verbose_name='chakra max health'),
        ),
        migrations.AddField(
            model_name='historicalhero',
            name='chakra_max_shield',
            field=models.IntegerField(default=0, verbose_name='chakra max shield'),
        ),
        migrations.AddField(
            model_name='historicalhero',
            name='chakra_moniker',
            field=models.CharField(db_index=True, default='moniker', max_length=50, verbose_name='chakra moniker'),
        ),
    ]
