# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_auto_20171218_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchest',
            name='coin_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='coin quantity'),
        ),
        migrations.AlterField(
            model_name='userchest',
            name='gem_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='gem quantity'),
        ),
    ]
