# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_auto_20180225_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusercurrency',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='usercurrency',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='chakra_moniker',
            field=models.CharField(max_length=50, verbose_name='chakra moniker'),
        ),
        migrations.AlterField(
            model_name='historicalhero',
            name='chakra_moniker',
            field=models.CharField(max_length=50, verbose_name='chakra moniker'),
        ),
    ]
