# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_auto_20171218_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchest',
            old_name='coin_quantity',
            new_name='coin',
        ),
        migrations.RenameField(
            model_name='userchest',
            old_name='gem_quantity',
            new_name='gem',
        ),
    ]
