# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_auto_20171218_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='name',
        ),
        migrations.AddField(
            model_name='hero',
            name='enable_in_start',
            field=models.BooleanField(default=False, verbose_name='enable in start'),
        ),
        migrations.AddField(
            model_name='hero',
            name='moniker',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='moniker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('6109907b-9dcd-405f-85f9-d4c4e86a1a46'), editable=False, verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='unit',
            name='enable_in_start',
            field=models.BooleanField(default=False, verbose_name='enable in start'),
        ),
        migrations.AddField(
            model_name='unit',
            name='moniker',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='moniker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('6109907b-9dcd-405f-85f9-d4c4e86a1a46'), editable=False, verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='userunits',
            name='cur_card_count',
            field=models.PositiveIntegerField(default=1, verbose_name='cur card count'),
        ),
        migrations.AddField(
            model_name='userunits',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='userunits',
            name='next_upgrade_card_count',
            field=models.PositiveIntegerField(default=0, verbose_name='next upgrade card count'),
        ),
        migrations.AddField(
            model_name='userunits',
            name='next_upgrade_coin_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='next Upgrade Coin Cost'),
        ),
    ]
