# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 12:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_herospelleffect'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitSpellEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('is_multi_part', models.BooleanField(default=False, verbose_name='is multi part')),
                ('target_character_id', models.FloatField(default=0, verbose_name='target character id')),
                ('effect_on_character', multiselectfield.db.fields.MultiSelectField(choices=[('None', 'None'), ('Appear', 'Appear'), ('NormalDamage', 'NormalDamage'), ('SeriousDamage', 'SeriousDamage'), ('Nerf', 'Nerf'), ('Buff', 'Buff'), ('Miss', 'Miss'), ('Dodge', 'Dodge'), ('Burn', 'Burn'), ('Fear', 'Fear'), ('Taunt', 'Taunt'), ('Revive', 'Revive'), ('Prepare', 'Prepare'), ('Protect', 'Protect')], max_length=98, null=True)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='objects.UnitSpell', verbose_name='effect')),
            ],
            options={
                'db_table': 'unit_spell_effects',
                'verbose_name': 'unit_spell_effect',
                'verbose_name_plural': 'unit_spell_effects',
            },
        ),
        migrations.AlterField(
            model_name='herospelleffect',
            name='effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='objects.HeroSpell', verbose_name='effect'),
        ),
    ]
