# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_auto_20171230_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='name',
        ),
        migrations.AlterField(
            model_name='hero',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('b2455067-29a2-442f-a380-5a2de0820de3'), editable=False, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('b2455067-29a2-442f-a380-5a2de0820de3'), editable=False, verbose_name='unique id'),
        ),
    ]
