# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 10:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0011_auto_20180228_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChakraSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('char_spells_index', models.IntegerField(default=0, verbose_name='char spells index')),
                ('spell_name', models.CharField(default='', max_length=100, verbose_name='spell name')),
                ('spell_type', models.CharField(choices=[('Magic', 'Magic'), ('Secret', 'Secret')], default='Magic', max_length=50, verbose_name='spell type')),
                ('generated_action_point', models.IntegerField(default=0, verbose_name='generated action point')),
                ('need_action_point', models.PositiveIntegerField(default=0, verbose_name='need action point')),
                ('cool_down_duration', models.PositiveIntegerField(default=0, verbose_name='cool down duration')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chakra_spells', to='objects.Hero', verbose_name='hero')),
            ],
            options={
                'db_table': 'chakra_spells',
                'verbose_name': 'chakra_spell',
                'verbose_name_plural': 'chakra_spells',
            },
        ),
        migrations.CreateModel(
            name='ChakraSpellEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('is_multi_part', models.BooleanField(default=False, verbose_name='is multi part')),
                ('target_character_id', models.FloatField(default=0, verbose_name='target character id')),
                ('effect_on_character', multiselectfield.db.fields.MultiSelectField(choices=[('None', 'None'), ('Appear', 'Appear'), ('NormalDamage', 'NormalDamage'), ('SeriousDamage', 'SeriousDamage'), ('Nerf', 'Nerf'), ('Buff', 'Buff'), ('Miss', 'Miss'), ('Dodge', 'Dodge'), ('Burn', 'Burn'), ('Fear', 'Fear'), ('Taunt', 'Taunt'), ('Revive', 'Revive'), ('Prepare', 'Prepare'), ('Protect', 'Protect'), ('shout', 'shout')], max_length=104, null=True)),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='duration turn')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chakra_effects', to='objects.ChakraSpell', verbose_name='effect')),
            ],
            options={
                'db_table': 'chakra_spell_effects',
                'verbose_name': 'chakra_spell_effect',
                'verbose_name_plural': 'chakra_spell_effects',
            },
        ),
        migrations.AlterModelOptions(
            name='herospell',
            options={'verbose_name': 'chakra_spell', 'verbose_name_plural': 'hero_spells'},
        ),
        migrations.RemoveField(
            model_name='herospell',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='herospell',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='unitspell',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='unitspell',
            name='duration',
        ),
        migrations.AddField(
            model_name='herospelleffect',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='duration turn'),
        ),
        migrations.AddField(
            model_name='unitspelleffect',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='duration turn'),
        ),
        migrations.AlterField(
            model_name='herospell',
            name='spell_type',
            field=models.CharField(choices=[('Magic', 'Magic'), ('Secret', 'Secret')], default='Magic', max_length=50, verbose_name='spell type'),
        ),
        migrations.AlterField(
            model_name='herospelleffect',
            name='effect_on_character',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('None', 'None'), ('Appear', 'Appear'), ('NormalDamage', 'NormalDamage'), ('SeriousDamage', 'SeriousDamage'), ('Nerf', 'Nerf'), ('Buff', 'Buff'), ('Miss', 'Miss'), ('Dodge', 'Dodge'), ('Burn', 'Burn'), ('Fear', 'Fear'), ('Taunt', 'Taunt'), ('Revive', 'Revive'), ('Prepare', 'Prepare'), ('Protect', 'Protect'), ('shout', 'shout')], max_length=104, null=True),
        ),
        migrations.AlterField(
            model_name='unitspell',
            name='spell_type',
            field=models.CharField(choices=[('Magic', 'Magic'), ('Secret', 'Secret')], default='Magic', max_length=50, verbose_name='spell type'),
        ),
        migrations.AlterField(
            model_name='unitspelleffect',
            name='effect_on_character',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('None', 'None'), ('Appear', 'Appear'), ('NormalDamage', 'NormalDamage'), ('SeriousDamage', 'SeriousDamage'), ('Nerf', 'Nerf'), ('Buff', 'Buff'), ('Miss', 'Miss'), ('Dodge', 'Dodge'), ('Burn', 'Burn'), ('Fear', 'Fear'), ('Taunt', 'Taunt'), ('Revive', 'Revive'), ('Prepare', 'Prepare'), ('Protect', 'Protect'), ('shout', 'shout')], max_length=104, null=True),
        ),
    ]
