# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0011_auto_20171230_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='attack_type',
            field=models.CharField(choices=[('NORMAL', 'normal'), ('SKILLSHOT', 'skillshot')], default='normal', max_length=50, verbose_name='attack type'),
        ),
        migrations.AddField(
            model_name='unit',
            name='attack_type',
            field=models.CharField(choices=[('NORMAL', 'normal'), ('SKILLSHOT', 'skillshot')], default='normal', max_length=50, verbose_name='attack type'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('d80ca625-8381-4a5d-803d-281076c9f36d'), editable=False, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('d80ca625-8381-4a5d-803d-281076c9f36d'), editable=False, verbose_name='unique id'),
        ),
    ]
