# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_auto_20180303_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='chakraspell',
            name='action_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Automatic', 'Automatic')], default='Normal', max_length=20, verbose_name='action type'),
        ),
        migrations.AddField(
            model_name='herospell',
            name='action_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Automatic', 'Automatic')], default='Normal', max_length=20, verbose_name='action type'),
        ),
        migrations.AddField(
            model_name='unitspell',
            name='action_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Automatic', 'Automatic')], default='Normal', max_length=20, verbose_name='action type'),
        ),
    ]
