# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_auto_20171230_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='image_logo',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='image',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='image_logo',
        ),
        migrations.AlterField(
            model_name='hero',
            name='attack_type',
            field=models.CharField(choices=[('NORMAL', 'normal'), ('SKILLSHOT', 'skillshot'), ('AUTOMATIC', 'automatic')], default='normal', max_length=50, verbose_name='attack type'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('fb377c5b-ccfa-464d-9aa2-90694b4389d8'), editable=False, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='attack_type',
            field=models.CharField(choices=[('NORMAL', 'normal'), ('SKILLSHOT', 'skillshot'), ('AUTOMATIC', 'automatic')], default='normal', max_length=50, verbose_name='attack type'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('fb377c5b-ccfa-464d-9aa2-90694b4389d8'), editable=False, verbose_name='unique id'),
        ),
    ]
