# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_auto_20180303_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
