# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_auto_20171230_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='chakra_attack',
            field=models.IntegerField(default=10, verbose_name='chakra attack'),
        ),
        migrations.AddField(
            model_name='hero',
            name='chakra_critical_chance',
            field=models.FloatField(default=0.01, verbose_name='chakra critical chance'),
        ),
        migrations.AddField(
            model_name='hero',
            name='chakra_critical_ratio',
            field=models.FloatField(default=0.01, verbose_name='chakra critical ratio'),
        ),
        migrations.AddField(
            model_name='hero',
            name='chakra_dodge_chance',
            field=models.FloatField(default=0.0, verbose_name='chakra dodge chance'),
        ),
        migrations.AddField(
            model_name='hero',
            name='chakra_health',
            field=models.IntegerField(default=100, verbose_name='chakra health'),
        ),
        migrations.AddField(
            model_name='hero',
            name='chakra_miss_chance',
            field=models.FloatField(default=0.0, verbose_name='chakra miss chance'),
        ),
        migrations.AddField(
            model_name='hero',
            name='chakra_shield',
            field=models.IntegerField(default=0, verbose_name='chakra shield'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('95465856-2068-4b11-8f18-1338a04fe6ec'), editable=False, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('95465856-2068-4b11-8f18-1338a04fe6ec'), editable=False, verbose_name='unique id'),
        ),
    ]
