# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0014_auto_20171230_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='moniker',
            field=models.CharField(max_length=50, unique=True, verbose_name='moniker'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('eba978c0-6daf-44c5-8e61-d3cf0c8f754f'), editable=False, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='moniker',
            field=models.CharField(max_length=50, unique=True, verbose_name='moniker'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('eba978c0-6daf-44c5-8e61-d3cf0c8f754f'), editable=False, verbose_name='unique id'),
        ),
    ]
