# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0015_auto_20171230_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('c2e2d1cd-4c4b-49a9-a906-33c3ab3c1c74'), editable=False, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('c2e2d1cd-4c4b-49a9-a906-33c3ab3c1c74'), editable=False, verbose_name='unique id'),
        ),
    ]
