# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0016_auto_20180304_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluserchest',
            old_name='cards',
            new_name='reward_data',
        ),
        migrations.RenameField(
            model_name='userchest',
            old_name='cards',
            new_name='reward_data',
        ),
    ]
