# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 12:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0016_auto_20171230_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
            ],
            options={
                'db_table': 'hero_units',
                'verbose_name': 'hero_unit',
                'verbose_name_plural': 'hero_units',
            },
        ),
        migrations.AlterField(
            model_name='hero',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('c68c517f-7505-44c8-b9d6-822aa19b39db'), editable=False, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('c68c517f-7505-44c8-b9d6-822aa19b39db'), editable=False, verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='herounits',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='objects.Hero', verbose_name='Hero'),
        ),
        migrations.AddField(
            model_name='herounits',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heroes', to='objects.Unit', verbose_name='Units'),
        ),
        migrations.AlterUniqueTogether(
            name='herounits',
            unique_together=set([('hero', 'unit')]),
        ),
    ]
