# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0017_auto_20171230_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='herounits',
            name='enable_hero',
            field=models.BooleanField(default=False, verbose_name='enable hero'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('85c2d9c3-691b-432e-8d73-8bb57acc4d28'), editable=False, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('85c2d9c3-691b-432e-8d73-8bb57acc4d28'), editable=False, verbose_name='unique id'),
        ),
    ]
