# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0017_auto_20180307_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusercurrency',
            name='can_change_name',
            field=models.BooleanField(default=True, verbose_name='can change name'),
        ),
        migrations.AddField(
            model_name='usercurrency',
            name='can_change_name',
            field=models.BooleanField(default=True, verbose_name='can change name'),
        ),
    ]
