# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0018_auto_20171230_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='unit_list',
            field=models.ManyToManyField(related_name='hero_unit', through='objects.HeroUnits', to='objects.Unit'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('2f88dcf2-1464-41a5-a201-2a98d7036466'), editable=False, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='herounits',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_hero', to='objects.Hero'),
        ),
        migrations.AlterField(
            model_name='herounits',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_heroes', to='objects.Unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('2f88dcf2-1464-41a5-a201-2a98d7036466'), editable=False, verbose_name='unique id'),
        ),
    ]
