# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 14:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0018_auto_20180310_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('app_data', django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True, verbose_name='app config')),
                ('enable', models.BooleanField(default=False, verbose_name='enable')),
            ],
            options={
                'db_table': 'app_configs',
                'verbose_name': 'app_config',
                'verbose_name_plural': 'app_configs',
            },
        ),
    ]
