# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0019_auto_20171230_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='unit_list',
        ),
        migrations.AddField(
            model_name='hero',
            name='units',
            field=models.ManyToManyField(related_name='hero', through='objects.HeroUnits', to='objects.Unit'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('2f551d8f-a78b-458c-b96d-7c1595a1827e'), editable=False, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('2f551d8f-a78b-458c-b96d-7c1595a1827e'), editable=False, verbose_name='unique id'),
        ),
    ]
