# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0020_auto_20171231_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='heroes',
            field=models.ManyToManyField(related_name='hero', through='objects.HeroUnits', to='objects.Hero'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('30fc06d9-1876-423f-8422-33ae2c5996eb'), editable=False, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('30fc06d9-1876-423f-8422-33ae2c5996eb'), editable=False, verbose_name='unique id'),
        ),
    ]
