# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0020_auto_20180314_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('helmet', 'helmet'), ('weapon', 'weapon'), ('Armor', 'Armor'), ('Accessory_1', 'Accessory_1'), ('Accessory_2', 'Accessory_2'), ('Accessory_3', 'Accessory_3')], default='helmet', max_length=50, null=True, verbose_name='item type'),
        ),
    ]
