# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 07:13
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0021_auto_20171231_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('enable_hero', models.BooleanField(default=False, verbose_name='enable hero')),
            ],
            options={
                'db_table': 'user_hero',
                'verbose_name': 'user_hero',
                'verbose_name_plural': 'user_hero',
            },
        ),
        migrations.RemoveField(
            model_name='herounits',
            name='enable_hero',
        ),
        migrations.AlterField(
            model_name='hero',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('d4bbd1c5-3769-44e9-a761-8b0e25c09389'), editable=False, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('d4bbd1c5-3769-44e9-a761-8b0e25c09389'), editable=False, verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='userhero',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hero', to='objects.Hero'),
        ),
        migrations.AddField(
            model_name='userhero',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hero',
            name='user',
            field=models.ManyToManyField(related_name='hero', through='objects.UserHero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userhero',
            unique_together=set([('user', 'hero')]),
        ),
    ]
