# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0021_auto_20180410_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chakraspell',
            name='spell_type',
            field=models.CharField(choices=[('Magic', 'Magic'), ('Chakra', 'Chakra'), ('Secret', 'Secret')], default='Magic', max_length=50, verbose_name='spell type'),
        ),
        migrations.AlterField(
            model_name='herospell',
            name='spell_type',
            field=models.CharField(choices=[('Magic', 'Magic'), ('Chakra', 'Chakra'), ('Secret', 'Secret')], default='Magic', max_length=50, verbose_name='spell type'),
        ),
        migrations.AlterField(
            model_name='unitspell',
            name='spell_type',
            field=models.CharField(choices=[('Magic', 'Magic'), ('Chakra', 'Chakra'), ('Secret', 'Secret')], default='Magic', max_length=50, verbose_name='spell type'),
        ),
    ]
