# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0022_auto_20180428_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunit',
            name='unlock',
            field=models.BooleanField(default=False, verbose_name='show box for user'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unlock',
            field=models.BooleanField(default=False, verbose_name='show box for user'),
        ),
    ]
