# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 10:47
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0022_auto_20171231_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity card')),
            ],
            options={
                'db_table': 'user_card',
                'verbose_name': 'user_card',
                'verbose_name_plural': 'user_cards',
            },
        ),
        migrations.AlterField(
            model_name='hero',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('c1a82c39-90c0-4843-ac19-81c228feb83f'), editable=False, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('c1a82c39-90c0-4843-ac19-81c228feb83f'), editable=False, verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='objects.Unit', verbose_name='character'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='username'),
        ),
    ]
