# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0023_auto_20180430_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalunit',
            name='unlock',
            field=models.BooleanField(default=False, verbose_name='unlock'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unlock',
            field=models.BooleanField(default=False, verbose_name='unlock'),
        ),
    ]
