# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 12:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0023_auto_20171231_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('31df92cf-a703-407a-85b2-17943ad7789f'), editable=False, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('31df92cf-a703-407a-85b2-17943ad7789f'), editable=False, verbose_name='unique id'),
        ),
        migrations.AlterUniqueTogether(
            name='usercard',
            unique_together=set([('user', 'character')]),
        ),
    ]
