# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0024_auto_20180430_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusercurrency',
            name='ban_user',
            field=models.BooleanField(default=False, verbose_name='ban user'),
        ),
        migrations.AddField(
            model_name='usercurrency',
            name='ban_user',
            field=models.BooleanField(default=False, verbose_name='ban user'),
        ),
    ]
