# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0025_auto_20171231_1237'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userunits',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userunits',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='userunits',
            name='user',
        ),
        migrations.AddField(
            model_name='usercard',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='next_upgrade_card_count',
            field=models.PositiveIntegerField(default=0, verbose_name='next upgrade card count'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='next_upgrade_coin_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='next Upgrade Coin Cost'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('ef715cbc-8462-4771-8a77-1dbc434d6b35'), editable=False, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('ef715cbc-8462-4771-8a77-1dbc434d6b35'), editable=False, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='user',
            field=models.ManyToManyField(related_name='units', through='objects.UserCard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserUnits',
        ),
    ]
