# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 08:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0025_auto_20180512_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('device_model', models.CharField(max_length=100, verbose_name='device model')),
                ('device_id', models.CharField(max_length=500, verbose_name='device model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='objects.UserCurrency', verbose_name='user')),
            ],
            options={
                'db_table': 'devices',
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
            },
        ),
    ]
