# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0026_device'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('user', 'device_id')]),
        ),
    ]
