# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 11:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import objects.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0027_auto_20180101_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('min_coin', models.PositiveIntegerField(default=0, verbose_name='min coin')),
                ('max_coin', models.PositiveIntegerField(default=0, verbose_name='max coin')),
                ('min_gem', models.PositiveIntegerField(default=0, verbose_name='min gem')),
                ('max_gem', models.PositiveIntegerField(default=0, verbose_name='max gem')),
                ('new_card_chance', models.PositiveIntegerField(default=1, validators=[objects.validators.validate_percent], verbose_name='new card chance percentage')),
                ('hero_card', models.PositiveIntegerField(default=0, verbose_name='hero card count')),
                ('unit_card', models.PositiveIntegerField(default=3, verbose_name='unit card count')),
            ],
            options={
                'db_table': 'chest',
                'verbose_name': 'chest',
                'verbose_name_plural': 'chest',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('min_score', models.PositiveIntegerField(default=0, verbose_name='score for enter the league')),
                ('description', models.TextField(default='', null=True, verbose_name='description')),
            ],
            options={
                'db_table': 'leagues',
                'verbose_name': 'league',
                'verbose_name_plural': 'leagues',
            },
        ),
        migrations.AlterField(
            model_name='hero',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='chest',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.League', verbose_name='chest'),
        ),
    ]
