# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0028_auto_20180102_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='chest',
            name='chest_type',
            field=models.CharField(default='w', max_length=50, verbose_name='chest type'),
        ),
    ]
