# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0029_chest_chest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chest',
            name='chest_type',
            field=models.CharField(choices=[('w', 'wooden'), ('s', 'silver'), ('g', 'gold'), ('c', 'crystal')], default='w', max_length=50, verbose_name='chest type'),
        ),
    ]
