# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0030_auto_20180102_1353'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chest',
            unique_together=set([('league', 'chest_type')]),
        ),
    ]
