# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0030_auto_20180519_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusercurrency',
            name='tutorial_done',
            field=models.BooleanField(default=False, verbose_name='tutorial'),
        ),
        migrations.AddField(
            model_name='usercurrency',
            name='tutorial_done',
            field=models.BooleanField(default=False, verbose_name='tutorial'),
        ),
    ]
