# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0031_auto_20180102_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chest',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chests', to='objects.League', verbose_name='chest'),
        ),
    ]
