# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0032_auto_20180102_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserChest',
            new_name='UserCurrency',
        ),
    ]
