# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 11:09
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0033_auto_20180103_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('chest_type', models.CharField(choices=[('free', 'FREE'), ('non-free', 'NON-FREE')], max_length=50, verbose_name='chest type')),
                ('chest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='objects.Chest', verbose_name='chest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chests', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'user_chests',
                'verbose_name': 'user_chest',
                'verbose_name_plural': 'user_chest',
            },
        ),
    ]
