# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0034_auto_20180519_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunit',
            name='starting_unit',
            field=models.BooleanField(default=False, verbose_name='starting unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='starting_unit',
            field=models.BooleanField(default=False, verbose_name='starting unit'),
        ),
    ]
