# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0034_userchest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchest',
            name='status',
            field=models.CharField(choices=[('close', 'close'), ('opening', 'opening'), ('ready', 'ready')], default='close', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='userchest',
            name='chest_type',
            field=models.CharField(choices=[('free', 'FREE'), ('non-free', 'NON-FREE')], default='free', max_length=50, verbose_name='chest type'),
        ),
    ]
