# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 13:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0035_auto_20180103_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchest',
            name='cards',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, verbose_name='cards'),
        ),
        migrations.AddField(
            model_name='userchest',
            name='sequence_number',
            field=models.PositiveIntegerField(default=1, verbose_name='sequence number'),
        ),
    ]
