# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 14:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0035_auto_20180527_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('bot_name', models.CharField(max_length=100, verbose_name='bot name')),
                ('min_trophy', models.IntegerField(verbose_name='min trophy')),
                ('max_trophy', models.IntegerField(verbose_name='max trophy')),
                ('sum_levels', models.IntegerField(verbose_name='sum levels')),
                ('min_levels', models.IntegerField(verbose_name='min levels')),
                ('max_levels', models.IntegerField(verbose_name='max levels')),
            ],
            options={
                'db_table': 'bots',
                'verbose_name': 'bot',
                'verbose_name_plural': 'bots',
            },
        ),
    ]
