# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 13:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0036_auto_20180103_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchest',
            name='cards',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True, verbose_name='cards'),
        ),
    ]
