# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0036_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bot_ai',
            field=models.FloatField(blank=True, null=True, verbose_name='bot ai'),
        ),
    ]
