# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0037_bot_bot_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='max_level_hero',
            field=models.IntegerField(blank=True, null=True, verbose_name='max level hero'),
        ),
        migrations.AddField(
            model_name='bot',
            name='min_level_hero',
            field=models.IntegerField(blank=True, null=True, verbose_name='min level hero'),
        ),
    ]
