# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0038_auto_20180609_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='bot name'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='max_levels',
            field=models.IntegerField(blank=True, null=True, verbose_name='max levels'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='max_trophy',
            field=models.IntegerField(blank=True, null=True, verbose_name='max trophy'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='min_levels',
            field=models.IntegerField(blank=True, null=True, verbose_name='min levels'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='min_trophy',
            field=models.IntegerField(blank=True, null=True, verbose_name='min trophy'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='sum_levels',
            field=models.IntegerField(blank=True, null=True, verbose_name='sum levels'),
        ),
    ]
