# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 14:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0039_auto_20180610_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('inc_count', models.PositiveIntegerField(default=0, verbose_name='inc count')),
                ('dec_count', models.PositiveIntegerField(default=0, verbose_name='dec count')),
                ('close_league', models.BooleanField(default=False, verbose_name='close')),
            ],
            options={
                'db_table': 'created_leagues',
                'verbose_name': 'created_league',
                'verbose_name_plural': 'created_leagues',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('league_name', models.CharField(max_length=250, verbose_name='league name')),
                ('capacity', models.PositiveIntegerField(default=50, verbose_name='capacity')),
                ('step_number', models.IntegerField(db_index=True, default=0, unique=True, verbose_name='step number')),
                ('league_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=10, verbose_name='league type')),
                ('min_trophy', models.IntegerField(blank=True, null=True, verbose_name='min trophy')),
                ('max_trophy', models.IntegerField(blank=True, null=True, verbose_name='max trophy')),
                ('playoff_range', models.IntegerField(blank=True, null=True, verbose_name='playoff range')),
                ('playoff_count', models.IntegerField(blank=True, null=True, verbose_name='playoff count')),
            ],
            options={
                'db_table': 'leagues',
                'verbose_name': 'league',
                'verbose_name_plural': 'leagues',
            },
        ),
        migrations.CreateModel(
            name='LeagueUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='objects.CreatedLeague', verbose_name='created_leagues')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='objects.UserCurrency', verbose_name='player')),
            ],
            options={
                'db_table': 'league_user',
                'verbose_name': 'league_user',
                'verbose_name_plural': 'league_user',
            },
        ),
        migrations.AddField(
            model_name='createdleague',
            name='base_league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_leagues', to='objects.League', verbose_name='league'),
        ),
        migrations.AlterUniqueTogether(
            name='leagueuser',
            unique_together=set([('player', 'league')]),
        ),
    ]
