# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0039_auto_20180103_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chest',
            name='chest_type',
            field=models.CharField(choices=[('W', 'wooden'), ('S', 'silver'), ('G', 'gold'), ('C', 'crystal')], default='w', max_length=50, verbose_name='chest type'),
        ),
    ]
