# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0040_auto_20180618_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createdleague',
            name='close_league',
        ),
        migrations.AddField(
            model_name='leagueuser',
            name='close_league',
            field=models.BooleanField(default=False, verbose_name='close'),
        ),
        migrations.AddField(
            model_name='leagueuser',
            name='score',
            field=models.PositiveIntegerField(default=50, verbose_name='score'),
        ),
    ]
