# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0042_auto_20180106_0750'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalLeague',
            new_name='HistoricalLeagueInfo',
        ),
        migrations.RenameModel(
            old_name='League',
            new_name='LeagueInfo',
        ),
        migrations.RenameField(
            model_name='chest',
            old_name='league',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='historicalchest',
            old_name='league',
            new_name='info',
        ),
        migrations.AlterField(
            model_name='chest',
            name='chest_type',
            field=models.CharField(choices=[('W', 'wooden'), ('S', 'silver'), ('G', 'gold'), ('C', 'crystal')], default='W', max_length=50, verbose_name='chest type'),
        ),
        migrations.AlterField(
            model_name='historicalchest',
            name='chest_type',
            field=models.CharField(choices=[('W', 'wooden'), ('S', 'silver'), ('G', 'gold'), ('C', 'crystal')], default='W', max_length=50, verbose_name='chest type'),
        ),
        migrations.AlterUniqueTogether(
            name='chest',
            unique_together=set([('info', 'chest_type')]),
        ),
    ]
