# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 12:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0042_auto_20180623_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaguePrize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('gem', models.PositiveIntegerField(default=0, verbose_name='gem')),
                ('coin', models.PositiveIntegerField(default=0, verbose_name='gem')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='level')),
            ],
            options={
                'db_table': 'prizes',
                'verbose_name': 'prize',
                'verbose_name_plural': 'prizes',
            },
        ),
        migrations.AddField(
            model_name='league',
            name='league_step',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='league step'),
        ),
        migrations.AddField(
            model_name='leagueprize',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='objects.League', verbose_name='league'),
        ),
        migrations.AlterUniqueTogether(
            name='leagueprize',
            unique_together=set([('level', 'league')]),
        ),
    ]
