# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0043_auto_20180624_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='demoting_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='demoting count'),
        ),
        migrations.AddField(
            model_name='league',
            name='promoting_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='promoting count'),
        ),
        migrations.AlterField(
            model_name='leagueprize',
            name='coin',
            field=models.PositiveIntegerField(default=0, verbose_name='coin'),
        ),
    ]
