# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0043_auto_20180107_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalleagueinfo',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical league_info'},
        ),
        migrations.AlterModelOptions(
            name='leagueinfo',
            options={'verbose_name': 'league_info', 'verbose_name_plural': 'league_infoes'},
        ),
        migrations.AlterModelTable(
            name='leagueinfo',
            table='league_infoes',
        ),
    ]
