# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0044_auto_20180624_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='play_off_start_gem',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='play off start gem'),
        ),
        migrations.AddField(
            model_name='league',
            name='play_off_unlock_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='play off unlock score'),
        ),
    ]
