# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0044_auto_20180107_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='chest',
            name='skip_gem_count',
            field=models.PositiveIntegerField(default=5, verbose_name='skip gem count'),
        ),
        migrations.AddField(
            model_name='chest',
            name='time_to_open',
            field=models.PositiveIntegerField(default=2, verbose_name='time to open'),
        ),
        migrations.AddField(
            model_name='historicalchest',
            name='skip_gem_count',
            field=models.PositiveIntegerField(default=5, verbose_name='skip gem count'),
        ),
        migrations.AddField(
            model_name='historicalchest',
            name='time_to_open',
            field=models.PositiveIntegerField(default=2, verbose_name='time to open'),
        ),
    ]
