# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0045_auto_20180625_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='play_off_start_gem_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='play off start gem 1'),
        ),
        migrations.AddField(
            model_name='league',
            name='play_off_start_gem_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='play off start gem 2'),
        ),
        migrations.AlterField(
            model_name='league',
            name='play_off_start_gem',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='play off start gem '),
        ),
    ]
