# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0046_auto_20180110_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chest',
            old_name='skip_gem_count',
            new_name='opening_time',
        ),
        migrations.RenameField(
            model_name='historicalchest',
            old_name='skip_gem_count',
            new_name='opening_time',
        ),
    ]
