# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0046_auto_20180625_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueuser',
            name='play_of_count',
            field=models.PositiveIntegerField(default=0, verbose_name='play of count'),
        ),
        migrations.AddField(
            model_name='leagueuser',
            name='win_count',
            field=models.PositiveIntegerField(default=0, verbose_name='win count'),
        ),
    ]
