# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0047_auto_20180625_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueuser',
            name='play_of_count',
        ),
        migrations.AddField(
            model_name='leagueuser',
            name='play_off_count',
            field=models.PositiveIntegerField(default=0, verbose_name='play off count'),
        ),
        migrations.AddField(
            model_name='leagueuser',
            name='play_off_status',
            field=models.CharField(choices=[('disable', 'disable'), ('not_started', 'not_started'), ('start', 'start')], default='disable', max_length=50, verbose_name='play off status'),
        ),
    ]
