# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0047_auto_20180110_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chest',
            name='opening_time',
            field=models.PositiveIntegerField(default=5, verbose_name='opening time'),
        ),
        migrations.AlterField(
            model_name='historicalchest',
            name='opening_time',
            field=models.PositiveIntegerField(default=5, verbose_name='opening time'),
        ),
    ]
