# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0049_auto_20180110_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserchest',
            name='chest_opening_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='chest opening time'),
        ),
        migrations.AddField(
            model_name='userchest',
            name='chest_opening_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='chest opening time'),
        ),
    ]
