# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0049_leagueuser_match_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='league_type',
            field=models.CharField(choices=[('cooper', 'cooper'), ('bronze', 'bronze'), ('silver', 'silver'), ('gold', 'gold'), ('earth', 'earth'), ('platinum', 'platinum'), ('diamond', 'diamond')], default='cooper', max_length=10, verbose_name='league type'),
        ),
    ]
