# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 07:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0052_auto_20180626_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('coin', models.PositiveIntegerField(default=10, verbose_name='coin')),
                ('gem', models.PositiveIntegerField(default=10, verbose_name='gem')),
                ('is_used', models.BooleanField(default=False, verbose_name='used')),
                ('league_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='objects.LeagueUser', verbose_name='league_user')),
            ],
            options={
                'db_table': 'claims',
                'verbose_name': 'claim',
                'verbose_name_plural': 'claims',
            },
        ),
    ]
