# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0053_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueuser',
            name='league_change_status',
            field=models.CharField(choices=[('normal', 'normal'), ('promoting', 'promoted'), ('demoting', 'demoted')], default='normal', max_length=50, verbose_name='league change status'),
        ),
    ]
