# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0053_item'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('name', 'hero')]),
        ),
    ]
