# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0054_auto_20180115_1135'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='item',
            name='hero',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
