# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0054_leagueuser_league_change_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueuser',
            name='league_change_status',
            field=models.CharField(choices=[('normal', 'normal'), ('promoted', 'promoted'), ('demoted', 'demoted')], default='normal', max_length=50, verbose_name='league change status'),
        ),
    ]
