# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 07:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0055_auto_20180627_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('status', models.CharField(choices=[('win', 'win'), ('lose', 'lose')], default='win', max_length=5, verbose_name='status')),
                ('player_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='objects.LeagueUser', verbose_name='player')),
            ],
            options={
                'db_table': 'playoff',
                'verbose_name': 'playoff',
                'verbose_name_plural': 'playoffs',
            },
        ),
    ]
