# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0056_auto_20180115_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='critical_chance',
            field=models.FloatField(default=0, verbose_name='critical chance'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dodge_chance',
            field=models.FloatField(default=0, verbose_name='dodge chance'),
        ),
    ]
