# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0057_auto_20180115_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
