# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0057_playoff_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='win_promoting_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='win promoting count'),
        ),
    ]
