# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 13:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0058_league_win_promoting_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('end_date', models.DateTimeField(auto_now=True, verbose_name='global end date')),
                ('expired', models.BooleanField(default=False, verbose_name='leagues expired')),
            ],
            options={
                'db_table': 'league_times',
                'verbose_name': 'league time',
                'verbose_name_plural': 'league_times',
            },
        ),
    ]
