# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0058_auto_20180115_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('helmet', 'helmet'), ('weapon', 'weapon'), ('Armor', 'Armor')], default='helmet', max_length=50, null=True, verbose_name='item type'),
        ),
    ]
