# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0059_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='critical_ratio',
            field=models.FloatField(default=0, verbose_name='critical ratio'),
        ),
    ]
