# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0059_leaguetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguetime',
            name='end_date',
            field=models.DateTimeField(verbose_name='global end date'),
        ),
    ]
