# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0060_auto_20180115_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='level',
            field=models.PositiveIntegerField(default=0, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(choices=[('Biker', 'Biker'), ('Dimetry', 'Dimetry'), ('Lion', 'Lion'), ('Guerrilla', 'Guerrilla'), ('Knight', 'Knight'), ('Horn', 'Horn'), ('Mexican', 'Mexican'), ('Mexican', 'Mexican')], default='Biker', max_length=50, verbose_name='name'),
        ),
    ]
