# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0061_auto_20180707_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguetime',
            name='demoting_count',
            field=models.PositiveIntegerField(default=3, verbose_name='demoting count'),
        ),
        migrations.AddField(
            model_name='leaguetime',
            name='promoting_count',
            field=models.PositiveIntegerField(default=3, verbose_name='promoting count'),
        ),
    ]
