# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0061_auto_20180115_1504'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('name', 'hero', 'item_type')]),
        ),
    ]
