# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0062_auto_20180116_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(choices=[('Biker', 'Biker'), ('Dimetry', 'Dimetry'), ('Lion', 'Lion'), ('Guerrilla', 'Guerrilla'), ('Knight', 'Knight'), ('Horn', 'Horn'), ('Mexican', 'Mexican'), ('Naga', 'Naga'), ('Duff', 'Duff')], default='Biker', max_length=50, verbose_name='name'),
        ),
    ]
