# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0062_auto_20180708_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdleague',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='enable legue'),
        ),
    ]
