# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0063_createdleague_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueuser',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='score'),
        ),
    ]
