# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 12:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0065_auto_20180116_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserhero',
            name='selected_item',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=3, verbose_name='selected item'),
        ),
        migrations.AlterField(
            model_name='userhero',
            name='selected_item',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=3, verbose_name='selected item'),
        ),
    ]
