# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 12:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0066_auto_20180116_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserhero',
            name='selected_item',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='selected item'),
        ),
        migrations.AlterField(
            model_name='userhero',
            name='selected_item',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='selected item'),
        ),
    ]
