# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 07:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0066_auto_20180711_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('quantity', models.PositiveIntegerField(default=5, verbose_name='quantity')),
                ('win_rate_min', models.PositiveIntegerField(verbose_name='win rate min percent')),
                ('win_rate_max', models.PositiveIntegerField(verbose_name='win rate max percent')),
                ('type', models.CharField(choices=[('promote', 'promote'), ('normal', 'normal'), ('demote', 'demote')], max_length=10, verbose_name='type')),
                ('fake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='objects.Fake', verbose_name='fake')),
            ],
            options={
                'db_table': 'fake_details',
                'verbose_name': 'fake_detail',
                'verbose_name_plural': 'fake_details',
            },
        ),
        migrations.AlterUniqueTogether(
            name='fakedetail',
            unique_together=set([('type', 'fake')]),
        ),
    ]
