# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 08:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0068_auto_20180117_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserhero',
            name='selected_item',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True, verbose_name='selected item'),
        ),
        migrations.AlterField(
            model_name='userhero',
            name='selected_item',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True, verbose_name='selected item'),
        ),
    ]
