# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0068_auto_20180717_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusercard',
            name='used_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='used quantity'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='used_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='used quantity'),
        ),
    ]
