# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0069_auto_20180117_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserhero',
            name='level',
            field=models.PositiveIntegerField(default=0, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='userhero',
            name='level',
            field=models.PositiveIntegerField(default=0, verbose_name='level'),
        ),
    ]
