# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0069_auto_20180721_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserhero',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='used count'),
        ),
        migrations.AddField(
            model_name='userhero',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='used count'),
        ),
    ]
