# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0070_auto_20180722_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusercard',
            name='google_account',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='google account'),
        ),
        migrations.AddField(
            model_name='historicalusercard',
            name='google_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='google id'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='google_account',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='google account'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='google_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='google id'),
        ),
    ]
