# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0072_auto_20180728_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusercurrency',
            name='google_account',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='google account'),
        ),
        migrations.AlterField(
            model_name='historicalusercurrency',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='google id'),
        ),
        migrations.AlterField(
            model_name='usercurrency',
            name='google_account',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='google account'),
        ),
        migrations.AlterField(
            model_name='usercurrency',
            name='google_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='google id'),
        ),
    ]
