# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0074_auto_20180729_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunit',
            name='coming_soon',
            field=models.BooleanField(default=False, verbose_name='coming soon'),
        ),
        migrations.AddField(
            model_name='unit',
            name='coming_soon',
            field=models.BooleanField(default=False, verbose_name='coming soon'),
        ),
    ]
