# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0075_auto_20180811_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusercurrency',
            name='strike',
            field=models.IntegerField(default=0, verbose_name='strike'),
        ),
        migrations.AddField(
            model_name='usercurrency',
            name='strike',
            field=models.IntegerField(default=0, verbose_name='strike'),
        ),
    ]
