# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0078_auto_20180829_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusercurrency',
            name='strike',
            field=models.IntegerField(default=0, null=True, verbose_name='strike'),
        ),
        migrations.AlterField(
            model_name='usercurrency',
            name='strike',
            field=models.IntegerField(default=0, null=True, verbose_name='strike'),
        ),
    ]
