# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0079_auto_20180829_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusercurrency',
            name='google_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='google id'),
        ),
        migrations.AlterField(
            model_name='usercurrency',
            name='google_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='google id'),
        ),
    ]
