# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0080_auto_20180901_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusercurrency',
            name='strike',
            field=models.IntegerField(default=0, verbose_name='strike'),
        ),
        migrations.AlterField(
            model_name='usercurrency',
            name='strike',
            field=models.IntegerField(default=0, verbose_name='strike'),
        ),
    ]
