# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0082_auto_20181014_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusercurrency',
            name='reward_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='reward token'),
        ),
        migrations.AddField(
            model_name='usercurrency',
            name='reward_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='reward token'),
        ),
    ]
