# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0083_auto_20181027_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='chakraspell',
            name='rarity',
            field=models.CharField(choices=[('common', 'common'), ('rare', 'rare'), ('epic', 'epic')], default='common', max_length=10, verbose_name='rarity'),
        ),
        migrations.AddField(
            model_name='herospell',
            name='rarity',
            field=models.CharField(choices=[('common', 'common'), ('rare', 'rare'), ('epic', 'epic')], default='common', max_length=10, verbose_name='rarity'),
        ),
        migrations.AddField(
            model_name='historicalunit',
            name='rarity',
            field=models.CharField(choices=[('common', 'common'), ('rare', 'rare'), ('epic', 'epic')], default='common', max_length=10, verbose_name='rarity'),
        ),
        migrations.AddField(
            model_name='unit',
            name='rarity',
            field=models.CharField(choices=[('common', 'common'), ('rare', 'rare'), ('epic', 'epic')], default='common', max_length=10, verbose_name='rarity'),
        ),
        migrations.AddField(
            model_name='unitspell',
            name='rarity',
            field=models.CharField(choices=[('common', 'common'), ('rare', 'rare'), ('epic', 'epic')], default='common', max_length=10, verbose_name='rarity'),
        ),
    ]
