# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 08:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import objects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0084_auto_20181127_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCardSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('spell_id', models.IntegerField(validators=[objects.validators.validate_unit_spell], verbose_name='spell id')),
                ('spell_level', models.IntegerField(default=1, verbose_name='spell level')),
                ('spell_card_count', models.IntegerField(default=0, verbose_name='spell card count')),
                ('user_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_levels', to='objects.UserCard', verbose_name='user card')),
            ],
            options={
                'db_table': 'user_card_spells',
                'verbose_name': 'user_card_spell',
                'verbose_name_plural': 'user_card_spells',
            },
        ),
    ]
