# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0085_usercardspell'),
    ]

    operations = [
        migrations.AddField(
            model_name='chakraspell',
            name='base_update_level_coin',
            field=models.PositiveIntegerField(default=0, verbose_name='base update level coin'),
        ),
        migrations.AddField(
            model_name='herospell',
            name='base_update_level_coin',
            field=models.PositiveIntegerField(default=0, verbose_name='base update level coin'),
        ),
        migrations.AddField(
            model_name='unitspell',
            name='base_update_level_coin',
            field=models.PositiveIntegerField(default=0, verbose_name='base update level coin'),
        ),
    ]
