# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-02 14:08
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0086_auto_20181128_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercardspell',
            name='spell_id',
            field=models.IntegerField(validators=[common.validators.validate_unit_spell], verbose_name='spell id'),
        ),
    ]
