# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 10:03
from __future__ import unicode_literals

import common.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0087_auto_20181202_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChakraSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('spell_id', models.IntegerField(validators=[common.validators.validate_chakra_spell], verbose_name='spell id')),
                ('spell_level', models.IntegerField(default=1, verbose_name='spell level')),
                ('spell_card_count', models.IntegerField(default=0, verbose_name='spell card count')),
                ('user_hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chakra_spell_levels', to='objects.UserHero', verbose_name='user hero')),
            ],
            options={
                'db_table': 'user_chakra_spells',
                'verbose_name': 'user_chakra_spell',
                'verbose_name_plural': 'user_chakra_spells',
            },
        ),
        migrations.CreateModel(
            name='UserHeroSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('spell_id', models.IntegerField(validators=[common.validators.validate_hero_spell], verbose_name='spell id')),
                ('spell_level', models.IntegerField(default=1, verbose_name='spell level')),
                ('spell_card_count', models.IntegerField(default=0, verbose_name='spell card count')),
                ('user_hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_spell_levels', to='objects.UserHero', verbose_name='user hero')),
            ],
            options={
                'db_table': 'user_hero_spells',
                'verbose_name': 'user_hero_spell',
                'verbose_name_plural': 'user_hero_spells',
            },
        ),
    ]
