# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 14:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingGemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('shopping_type', models.CharField(choices=[('gem', 'gem'), ('coin', 'coin'), ('chest', 'chest'), ('offer', 'offer')], default='gem', max_length=50, verbose_name='shopping type')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='player')),
            ],
            options={
                'db_table': 'shopping_logs',
                'verbose_name': 'shopping_log',
                'verbose_name_plural': 'shopping_logs',
            },
        ),
    ]
