# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 10:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0068_auto_20180717_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('chest_type', models.CharField(choices=[('W', 'wooden'), ('S', 'silver'), ('G', 'gold'), ('C', 'crystal')], default='W', max_length=50, verbose_name='chest type')),
                ('min_coin', models.PositiveIntegerField(default=0, verbose_name='min coin')),
                ('max_coin', models.PositiveIntegerField(default=0, verbose_name='max coin')),
                ('min_gem', models.PositiveIntegerField(default=0, verbose_name='min gem')),
                ('max_gem', models.PositiveIntegerField(default=0, verbose_name='max gem')),
                ('min_troop', models.PositiveIntegerField(default=0, verbose_name='min troop')),
                ('max_troop', models.PositiveIntegerField(default=0, verbose_name='max troop')),
                ('min_hero', models.PositiveIntegerField(default=0, verbose_name='min hero')),
                ('max_hero', models.PositiveIntegerField(default=0, verbose_name='max hero')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='total')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctm_chests', to='objects.League', verbose_name='league')),
            ],
            options={
                'db_table': 'ctm',
                'verbose_name': 'ctm',
                'verbose_name_plural': 'ctm',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ctm',
            unique_together=set([('chest_type', 'league')]),
        ),
    ]
