# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_auto_20180718_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctm',
            name='count_card',
            field=models.PositiveIntegerField(default=0, verbose_name='count card'),
        ),
    ]
