# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0003_ctm_count_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctm',
            name='count_card',
        ),
        migrations.AddField(
            model_name='ctm',
            name='card_try',
            field=models.PositiveIntegerField(default=0, verbose_name='count try'),
        ),
    ]
