# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0004_auto_20180718_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctm',
            name='chance_hero',
            field=models.FloatField(default=0, verbose_name='chance hero'),
        ),
        migrations.AlterField(
            model_name='ctm',
            name='chance_troop',
            field=models.FloatField(default=0, verbose_name='chance troop'),
        ),
    ]
