# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 13:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0069_auto_20180721_1200'),
        ('system_settings', '0005_auto_20180718_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTMUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('enable', models.BooleanField(default=True, verbose_name='enable')),
                ('ctm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='system_settings.CTM', verbose_name='ctm')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctms', to='objects.Unit', verbose_name='unit')),
            ],
            options={
                'db_table': 'ctm_units',
                'verbose_name': 'ctm_unit',
                'verbose_name_plural': 'ctm_units',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ctmunit',
            unique_together=set([('ctm', 'unit')]),
        ),
    ]
