# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 14:33
from __future__ import unicode_literals

import base.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0007_auto_20180721_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMatchMaking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('bot_ai', base.fields.IntegerRangeField(default=0, verbose_name='bot ai')),
                ('strike_number', models.IntegerField(unique=True, verbose_name='strike number')),
                ('min_level', models.IntegerField(default=0, verbose_name='min level')),
                ('max_level', models.IntegerField(default=0, verbose_name='max level')),
                ('step_forward', models.IntegerField(default=0, verbose_name='step forward')),
                ('step_backward', models.IntegerField(default=0, verbose_name='step backward')),
            ],
            options={
                'db_table': 'bot_match_makings',
                'verbose_name': 'bot_match_making',
                'verbose_name_plural': 'bot_match_makings',
            },
        ),
    ]
