# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0008_botmatchmaking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctm',
            name='chest_type',
            field=models.CharField(choices=[('W', 'wooden'), ('S', 'silver'), ('G', 'gold'), ('C', 'crystal'), ('M', 'magical'), ('L', 'Legendary')], default='W', max_length=50, verbose_name='chest type'),
        ),
    ]
