# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 12:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0081_auto_20180930_1205'),
        ('system_settings', '0009_auto_20180826_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('bot_name', models.CharField(max_length=200, verbose_name='bot name')),
                ('enable', models.BooleanField(default=False, verbose_name='enable')),
            ],
            options={
                'db_table': 'custom_bots',
                'verbose_name': 'custom_bot',
                'verbose_name_plural': 'custom_bots',
            },
        ),
        migrations.CreateModel(
            name='CustomBotTroop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('level', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='level')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troops', to='system_settings.CustomBot', verbose_name='bot')),
                ('troop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_bots', to='objects.Unit', verbose_name='troop')),
            ],
            options={
                'db_table': 'custom_bot_troops',
                'verbose_name': 'custom_bot_troop',
                'verbose_name_plural': 'custom_bot_troops',
            },
        ),
        migrations.AlterUniqueTogether(
            name='custombottroop',
            unique_together=set([('troop', 'bot')]),
        ),
    ]
