# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0081_auto_20180930_1205'),
        ('system_settings', '0010_auto_20180930_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombot',
            name='units',
            field=models.ManyToManyField(related_name='bots', through='system_settings.CustomBotTroop', to='objects.Unit', verbose_name='units'),
        ),
    ]
