# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0082_auto_20181014_0722'),
        ('system_settings', '0011_custombot_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombottroop',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='objects.Hero', verbose_name='hero'),
        ),
    ]
