# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 08:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0014_custombot_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('token_desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='token description')),
                ('gem_reward', models.PositiveIntegerField(default=1000, verbose_name='gem reward')),
                ('coin_reward', models.PositiveIntegerField(default=1000, verbose_name='coin reward')),
                ('token', models.CharField(blank=True, max_length=200, null=True, verbose_name='token')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='expire date')),
            ],
            options={
                'db_table': 'custom_tokens',
                'verbose_name': 'custom_token',
                'verbose_name_plural': 'custom_tokens',
            },
        ),
    ]
