# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0015_customtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtoken',
            name='enable',
            field=models.BooleanField(default=False, verbose_name='enable'),
        ),
    ]
