# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0016_customtoken_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='token',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='token'),
        ),
    ]
