# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-02 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0018_userloginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctm',
            name='epic_chance',
            field=models.PositiveIntegerField(default=0, verbose_name='epic chance'),
        ),
        migrations.AddField(
            model_name='ctm',
            name='rare_chance',
            field=models.PositiveIntegerField(default=0, verbose_name='rare chance'),
        ),
    ]
