# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-02 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0086_auto_20181128_1325'),
        ('system_settings', '0019_auto_20181202_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctm',
            name='must_have_hero',
            field=models.ManyToManyField(to='objects.Hero', verbose_name='must have hero'),
        ),
    ]
