# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-02 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0022_ctm_must_have_spell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctm',
            name='must_have_hero',
            field=models.ManyToManyField(blank=True, to='objects.Hero', verbose_name='must have hero'),
        ),
        migrations.AlterField(
            model_name='ctm',
            name='must_have_spell',
            field=models.ManyToManyField(blank=True, to='objects.UnitSpell', verbose_name='must have unit spell'),
        ),
        migrations.AlterField(
            model_name='ctm',
            name='must_have_troop',
            field=models.ManyToManyField(blank=True, to='objects.Unit', verbose_name='must have troop'),
        ),
    ]
