# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-02 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0024_auto_20181202_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctm',
            name='chance_hero',
        ),
        migrations.RemoveField(
            model_name='ctm',
            name='chance_troop',
        ),
        migrations.RemoveField(
            model_name='ctm',
            name='max_hero',
        ),
        migrations.RemoveField(
            model_name='ctm',
            name='max_troop',
        ),
        migrations.RemoveField(
            model_name='ctm',
            name='min_hero',
        ),
        migrations.RemoveField(
            model_name='ctm',
            name='min_troop',
        ),
    ]
