# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0025_auto_20181202_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctm',
            name='max_have_hero',
            field=models.PositiveIntegerField(default=0, verbose_name='max have hero'),
        ),
        migrations.AddField(
            model_name='ctm',
            name='max_have_spell',
            field=models.PositiveIntegerField(default=0, verbose_name='max have spell'),
        ),
        migrations.AddField(
            model_name='ctm',
            name='max_have_troop',
            field=models.PositiveIntegerField(default=0, verbose_name='max have spell'),
        ),
        migrations.AddField(
            model_name='ctm',
            name='min_have_hero',
            field=models.PositiveIntegerField(default=0, verbose_name='min have hero'),
        ),
        migrations.AddField(
            model_name='ctm',
            name='min_have_spell',
            field=models.PositiveIntegerField(default=0, verbose_name='min have spell'),
        ),
        migrations.AddField(
            model_name='ctm',
            name='min_have_troop',
            field=models.PositiveIntegerField(default=0, verbose_name='min have spell'),
        ),
    ]
