# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0026_auto_20181203_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctm',
            name='must_have_hero_type',
            field=models.CharField(choices=[('random', 'random'), ('all', 'all')], default='random', max_length=10, verbose_name='must have hero type'),
        ),
        migrations.AddField(
            model_name='ctm',
            name='must_have_spell_type',
            field=models.CharField(choices=[('random', 'random'), ('all', 'all')], default='random', max_length=10, verbose_name='must have spell type'),
        ),
        migrations.AddField(
            model_name='ctm',
            name='must_have_troop_type',
            field=models.CharField(choices=[('random', 'random'), ('all', 'all')], default='random', max_length=10, verbose_name='must have troop type'),
        ),
    ]
