# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0027_auto_20181203_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctm',
            name='max_epic',
            field=models.PositiveIntegerField(default=0, verbose_name='max epic'),
        ),
        migrations.AddField(
            model_name='ctm',
            name='max_rare',
            field=models.PositiveIntegerField(default=0, verbose_name='max rare'),
        ),
        migrations.AddField(
            model_name='ctm',
            name='min_epic',
            field=models.PositiveIntegerField(default=0, verbose_name='min epic'),
        ),
        migrations.AddField(
            model_name='ctm',
            name='min_rare',
            field=models.PositiveIntegerField(default=0, verbose_name='min rare'),
        ),
    ]
