# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 07:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('name', models.CharField(max_length=50, verbose_name='shop name')),
                ('coins', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='coins')),
                ('gems', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='coins')),
                ('chests', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='chests')),
            ],
            options={
                'db_table': 'shops',
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('name', models.CharField(max_length=50, verbose_name='store name')),
            ],
            options={
                'db_table': 'stores',
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Store', verbose_name='store'),
        ),
    ]
