# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 08:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='gems',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='gems'),
        ),
    ]
