# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20180108_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='enable shop item'),
        ),
    ]
