# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 06:57
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0007_auto_20180429_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('store_purchase_token', models.CharField(max_length=50, unique=True, verbose_name='store purchase token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='user purchase')),
            ],
            options={
                'db_table': 'purchase_log',
                'verbose_name': 'purchase log',
                'verbose_name_plural': 'purchase logs',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='access_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='access token'),
        ),
        migrations.AddField(
            model_name='store',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='access token'),
        ),
    ]
