# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20180512_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='valid_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='valid name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='refresh token'),
        ),
    ]
