# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 09:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20180512_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselog',
            name='store_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='store params'),
        ),
        migrations.AddField(
            model_name='purchaselog',
            name='used_token',
            field=models.BooleanField(default=False, verbose_name='token used'),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='store_purchase_token',
            field=models.CharField(max_length=50, verbose_name='store purchase token'),
        ),
    ]
