# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 12:09
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0010_auto_20180512_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params')),
                ('type', models.CharField(choices=[('GEM', 'gem'), ('COIN', 'coin')], max_length=5, verbose_name='type currency')),
                ('quantity_used', models.IntegerField(default=0, verbose_name='quantity used')),
                ('type_buy', models.CharField(choices=[('GEM', 'gem'), ('COIN', 'coin')], max_length=10, verbose_name='buy type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_currencies', to=settings.AUTH_USER_MODEL, verbose_name='user purchase')),
            ],
            options={
                'db_table': 'currency_log',
                'verbose_name': 'currency log',
                'verbose_name_plural': 'currency logs',
            },
        ),
    ]
