# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_auto_20180512_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencylog',
            name='quantity_buy',
            field=models.IntegerField(default=0, verbose_name='quantity buy'),
        ),
    ]
