# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0017_auto_20180512_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_currencies', to='objects.UserCurrency', verbose_name='user purchase'),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='objects.UserCurrency', verbose_name='user purchase'),
        ),
    ]
