# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0020_auto_20180513_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselog',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shopping.Shop', verbose_name='shops'),
        ),
    ]
