# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0021_purchaselog_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='special_offer_time',
            field=models.DateTimeField(auto_now=True, verbose_name='special offer time'),
        ),
    ]
