# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0022_shop_special_offer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='special_offer_time',
            field=models.DateTimeField(verbose_name='special offer time'),
        ),
    ]
